### ISSUE TITLE
_id not autoincluded if used as link field

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#150]
```
Test1.addLinks({
	extra:{
		collection:Test2,
		type:'one',
		field:'_id'
	}
})
```
The _id field of Test1 will not show up in the result unless you add specifically add _id:1
(The use case for this is when you have a unique one to one relationship, you might want to just store them with the same _id)

**Comment by theodorDiaconu** [comment]
@Herteby this is such a weird use case, took me a while to wrap my mind around it. The reason is that in the "cleaning" process, if you did not specify the link "Storage field" it will remove it, without checking if it's actually _id ... I don't know if this should be fixed or no, adding additional checks for your use-case may have impact on the performance in other cases.

Thanks!

**Comment by Herteby** [comment]
Yeah actually it was just in my testing app for grapher-vue. Doesn't matter to me, just thought I'd report it.
