### ISSUE TITLE
Opinions on the limits of denormalization

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/grapher#194]
Hi,

Here is my use case:

Students use my app to ask `Questions`, and answer those questions with `Comments`.
They can also create `Feedbacks` for a lecture.

Lecturers can create `Polls`, but also `Questions`. 

All these `Collections` have a field called `lectureId`. When a particular lecture is loaded, I get Polls, Questions (and Comments for each question), and Feedbacks using subscriptions and multiple queries.

__My plan__ is to denormalize everything into the main Lecture-document. So, _one_ document will have fields called pollsCache, questionsCache (with nested commentsCache), feedbacksCache and so on... 

This way, I hope to make _one_ query to the DB to retrieve all the content. It is my understanding that MongoDB was designed exactly for embedding subdocuments, so this should be the "mongo-way".

But, since we have Meteor on top, I don't know if it can handle one big document with many subdocuments.

_My specific worries are:_

1. What if the document grows too big ( over > 16MB) ?
https://docs.mongodb.com/manual/reference/limits/

2. As the reads and writes to the one "master" document increase, does the load increase linearly, logarithmically or exponentially? 

Open to other thoughts as well. Let me know if something was unclear :)

**Comment by theodorDiaconu** [comment]
I honestly doubt you will have a single Lecture with so many questions, polls that will surpass even 1MB. So I wouldn't worry about that.

The load of write to master is not linear because now every change done in questions/polls will reflect itself in Lecture, so I'm thinking logarithmically. 

My personal advice is to avoid denormalization, as it makes no sense for your use-case. With grapher you are in the relational world again. Only use denormalization for advanced searching or for storing related data that rarely/never changes.

**Comment by nadeemja** [comment]
I appreciate your thoughts, @theodorDiaconu ! 

I will try without denormalization first. In any case, denormalization seems "plug and play" if I need it later.

Over and over again, I'm amazed by the work you have done with this package. I'm reading the docs 5 or 6 times from start to finish, and everytime I learn something new! :)

**Comment by theodorDiaconu** [comment]
Sure @nadeemja , if you feel that some things can be better explained, feel free to create an issue for it. There was a lot of sweat and tears put in Grapher and it's very complex behind the scenes but I tried to keep it as simple as possible.
