### ISSUE TITLE
Question: Sorting documents with pagination Grapher vs Pub/Sub

### ISSUE THREAD

**Issue by paulincai** [cult-of-coders/grapher#271]
Hi,

consider a chat window with a list inverted - newest messages at the bottom.

Let's say I need 25 of the most recent messages returned in inverse order.

With pub/sub this was easily done by publication with sort: { field: -1 } = publish most recent and subscribe sort: { field: 1 } = get those documents but sorted the other way around. In other words, I need the 25 most recent with the most recent at the end of the fetched array.

Can this be done with Grapher? I am not seeing options or something that I could use at the query exposure level.

Thank you,
Paul

**Comment by martineboh** [comment]
@paulincai Currently you can only do sorting using the Query Option $options and when creating a Named Query, not on exposure, though available via the options.sort parameter.

**Comment by paulincai** [comment]
@martineboh thanks a lot. I am using Named Queries and unfortunately couldn't find a way to get a reversed order. I think this would be a great feature (for some) cause re-ordering/sorting arrays is a pretty expensive process when done on either server side or client.

**Comment by theodorDiaconu** [comment]
@paulincai it's still pub/sub behind the scenes, you can have a query that uses the sort options you provided. If all your questions are answered feel free to close the issue

**Comment by paulincai** [comment]
Hi @theodorDiaconu, in my understanding, the query satisfies the subscription side options. Not sure I understand how I can do both, descending in pub and ascending in sub or a "one shot" query to avoid resorting the query result via mapping or other method. Any suggestion would be indeed very much appreciated. Are you by any chance thinking of something like ..e.g:  date: -1 and then by date: 1 as a second option?

**Comment by theodorDiaconu** [comment]
Hi @paulincai 

Read my comment here, there are some things related to your issues.
https://github.com/cult-of-coders/grapher/issues/251#issuecomment-409950341

Currently, do it manually, with the help of a library like sift: https://www.npmjs.com/package/sift
I want grapher to stay very light-weight, and at 1.3.x for a very long time. This is why I want to avoid new features for things you can do easily otherwise, introducing abstractions, we increase the entropy of something going wrong that somehow skipped the test-suite, and also increases the chances of refactoring.

Grapher still lacks things like, automated documentation so you don't have to go to an `API.md` to do your work. You don't have autocompletion of the entities in the client. I'm planning on writing it in typescript, and create just a simple bridge in Meteor package that hooks in automatically into configuring Grapher.

And then we can just create a sample another integration with `mongoose` and that's it. We move Grapher to NPM, getting nearer to the ecosystem.

Meteor is still boss in many things, but gradually it evolves into a:
Powerful & fast bundling system, Apollo/GraphQL Server, packaging model, useful stuff (Emails, Mongo, etc). Easy deployment, SSR, and many others.

Grapher will evolve into a server-side only npm package that aids Apollo, and will come in TypeScript packaging. Apollo won the client side battle, they are superior in every way.
