### ISSUE TITLE
Linker engine unset one-meta link sets field to {}

### ISSUE THREAD

**Issue by MisterQH** [cult-of-coders/grapher#337]
Hi! When using the linker engine to unset a `one-meta` link, instead of unsetting the link field in the DB, it sets it to `{}` and throws an error telling the ID is required.

Before `unset`:
`link: {_id: 12345, metadata: ...}`

After `unset`:
`link: {}`

This can be avoided by setting the `link.$._id` field to `optional: true`, but don't you think it should be better to just unset the link field in the DB instead of setting it to an empty object ?

**Comment by theodorDiaconu** [comment]
It's a smart and interesting question, and the behaviour at the same time can be confusing if we set the link as NULL/undefined, because you may need link: to be an object in your Schema also.

If you want custom behaviour you create your own unset() because this change won't solve anything. (Doing this at this stage may introduce BC to other projects)
