### ISSUE TITLE
Exposure in complex situations

### ISSUE THREAD

**Issue by damonmaria** [cult-of-coders/grapher#40]
Wow. I've just spent quite a bit of time building and refactoring something similar although far less ambitious that Grapher. I love how you have exposure working rather than named queries, but can see how it would get out of control in anything beyond a trivial app. 

What I ended up doing was defining 'views' on top of collections. These views provide similar firewalling and filtering based off the current user (what I call viewer). But by separating views from their collections I can have multiple views per collection. From the example at the top of your named query docs there could be a 'EndUser' view and a 'TeamMember' view. If these views were then used in links (rather than just Users) then you get around the problem as well as making your specification more closely match the domain. 

Would that be appropriate for Grapher? 

What I love about exposure is that so often what fields and links you want is a concern of the client, not the server. In the same way that the decision of reactive/publication or static/method is a client concern too. It would be great if exposure could get over this hurdle and become useful beyond trivial apps.

**Comment by theodorDiaconu** [comment]
@damonmaria thanks for the issue. The need for Named Queries arose from the fact that Exposures can get out of control easily. 

> But by separating views from their collections I can have multiple views per collection. From the example at the top of your named query docs there could be a 'EndUser' view and a 'TeamMember' view. If these views were then used in links (rather than just Users) then you get around the problem as well as making your specification more closely match the domain.

From my understanding you are saying we can create a sort of "Virtual Collections", that act exactly as Users, but have their own firewall specified. 

This is a very AWESOME idea. Because we can now separate concerns for exposure.

```
Employees = new VirtualCollection(Users, 'employees')
Employees.expose(config)
```
```
addLinks({
   employee: { collection: Employees, ... }
})
```

While this is a good idea, and it solves the problem of "Polymorphic" Collection Documents, I don't completely understand how it can lead to improved security because: an employee can be linked to an "order" or a "ticket" or something else. In order to allow access we need the context. Currently, exposure firewall is not very much "context" aware. Maybe the solution would be to provide the link he's comming from in the exposure ?

```
Users.expose({
      firewall(filters, options, userId, context) {
           if (context.from == 'orders') {
                    // a way to stop deep nest to user links in the firewall ?
                    // a way to allow only certain fields of it: Exposure.allowFields(filters, options, [fields])
           }
      }
})
```

My problem with this is that, the User exposure becomes too smart. Imagine doing this for 10 linked documents :)

I have also thought about this a lot! The idea I came up with is giving exposures ability to bypass other exporues.

```
Orders.expose({
     bypass: {
            employee: {
                   profile: 1,
                   otherField: 1
                   comments: {
                            $filters: {}
                   }
            }
     }
})
```

Now the client:
```
orders: {
     employee: { // Create a graph intersection with the bypass data :)
          profile: 1 
     }
}
```

Following on this idea, once we got the graph intersection, we can make this for every exposure:
```
Users.expose({
       body: { profile: 1, links: 1, etc: 1} // anything that comes will intersect with the allowed graph.
       firewall(filters, options, userId) {
              if (notAllowed) { this.body[link] = undefined }
       }
})
```

Looking forward to hear your thoughts. Cheers.

**Comment by theodorDiaconu** [comment]
Actually, this solves everything. By allowing a body object at exposure, and intersecting the graph with it in a propper manner, we gain the security exporues lacked. We should have the ability to control the body in the firewall.

```
// clone body for each firewall access.
firewall(filters, options, userId) {
     // at this stage, filters, options are cleaned, and this.body only contains the intersection of the request.
     if (something) { delete this.body[link]; }
     if (somethingElse) { _.extend(this.body, { ... }) }
}
// if body is specified, the linked collections'exposure will be bypassed.
body: {
    someField: 1
    xxx: 1
}
```

Doing this makes restrictLinks and restrictedFields unnecessary since you have control over the body in the firewall.

What do you think ?

**Comment by damonmaria** [comment]
Sorry for the delay. Been some long coding nights. Having looked at #41 I understand what you're saying above and I think it enables what I suggested plus makes the whole configuration a lot simpler and more powerful. And then firewalling by manipulating the body is a higher level way to do it. Very nice.

**Comment by theodorDiaconu** [comment]
issue transformed in 2 issues.
