### ISSUE TITLE
Grapher + React List Container

### ISSUE THREAD

**Issue by SachaG** [cult-of-coders/grapher#51]
Grapher looks really nice! It reminds me of a better version of [react-list-container](https://github.com/meteor-utilities/react-list-container), which we're currently using for Telescope. 

We're thinking about migrating to Apollo/GraphQL though, in which case I would probably no longer maintain react-list-container. If that happens, would it be ok to point people to Grapher or somehow merge both projects? What do you think?

**Comment by theodorDiaconu** [comment]
I see what you mean, but that concern is for "grapher-react". 
https://github.com/cult-of-coders/grapher-react/issues

We can build it upon. But instead of offering an integration for your package. I believe it would be better to take some parts of your code, keep ofcourse yourself as @author, and put it there. Idea of grapher-react is to 

```
<ListContainer collection={Posts} publication="posts.list" component={PostList}/>
```
...morphs into...
```
<ListContainer query={query} queryParameters?={} component={PostList} pagination={Component} />
```

Yep, I agree to point them to grapher-react, however only after this is properly implemented and tested.

**Comment by SachaG** [comment]
Oh perfect, I hadn't seen grapher-react :)
