### ISSUE TITLE
Query question

### ISSUE THREAD

**Issue by udiedrichsen** [cult-of-coders/grapher#56]
In your grapher live site:
http://grapher-live.cultofcoders.com/grapher

I hacked in the following query: 
```
{
	posts: {
        $filter({filters, params}) {
            filters.ownerId = params.ownerId
        },
        ownerId:1,
        title: 1
    }
}
```
as parameters:
```
{
    ownerId:"UNKNOWN"
}
```
To my surprise it shows all results from posts and not 0 results.
How can I get all fields of a collection ?
I tried:
```
{
 posts:1
}
```
or
```
{
 posts:{}
}
```
but I get only the ids.

Whats my mistake ?

**Comment by theodorDiaconu** [comment]
Yes, @udiedrichsen $filter() doesn't currently work in grapher-live. Pls add an issue there. I am aware of the issue I just did not have time to implement, will do soon. 

Regarding getting all fields, it's by design this way, we previously had an "$all" meta variable, but it was very easy to make mistakes, especially security mistakes, if the community will really need this I can make it available again, but only for schema-based items.
